spring:
  profiles:
      active: dev
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://114.115.172.242:8761//eureka/
#  instance:
#    preferIpAddress: true