apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - image: 517141035927.dkr.ecr.us-east-1.amazonaws.com/gateway:latest
          imagePullPolicy: Always
          name: gateway-service
          ports:
            - containerPort: 9000
              protocol: TCP