apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  labels:
    app: discovery-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - image: 517141035927.dkr.ecr.us-east-1.amazonaws.com/discovery:latest
          imagePullPolicy: Always
          name: user-service
          ports:
            - containerPort: 8761
              protocol: TCP
